### PR TITLE
feat: [v0.45.9] add minimum commission rate to x/staking (cherry-picked from aca9d7cb5a593f10e964fad8fd47c20486634c7c)

### PR DESCRIPTION
**Pull request by youngjoon-lee**
Cherry-picked from aca9d7cb5a593f10e964fad8fd47c20486634c7c for the new v0.45.9 release of cosmos/cosmos-sdk. This is supposed to be released as `medibloc/cosmos-sdk@v0.45.9-panacea`.

NOTE: The `test-rosetta` Github Actions is failing, but we can ignore it. We cannot run that action in our fork, as I understood.

### CODE REVIEW

**Review by gyuguen — APPROVED** [review]
Thanks!

**Review by 0xHansLee — APPROVED** [review]
👍

**Review by inchori — APPROVED** [review]
LGTM 👍 Thanks!

**Review by audtlr24 — APPROVED** [review]
LGTM

**Pull request merged**
